package table2svg

import (
	"fmt"
	"net/http"
)

func Handler(w http.ResponseWriter, r *http.Request) {

	// getパラメータの解析
	q := r.URL.Query()
	pageItem := q.Get("actorname")
	svgPage := fmt.Sprintf(`
	<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="2400" height="400" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<text x="400" y="250" style="text-anchor:start;font-size:20px;fill:red">%v </text>
</svg>
	`, pageItem)

	// Content-Type: image/svg+xml
	// Vary: Accept-Encoding
	w.Header().Set("Content-Type", "image/svg+xml; charset=utf-8")
	w.Header().Set("Vary", "Accept-Encoding")

	fmt.Fprint(w, svgPage)
}
